[package]
name = "overlink"

authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
libc.workspace = true
overlink-macros.workspace = true
